### ISSUE TITLE
Test CEDAR against latest Ingest Validation Tools branch

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-validation-tools#20]
As per Gesina:

you can find CEDAR test files/dirs in the phillips/tests branch under bad-cedar-* and good-cedar-* (still working on the branch, but the example files should be solid) https://github.com/hubmapconsortium/ingest-validation-tools/tree/phillips/tests/examples/dataset-examples

If you run into any errors, please let her know.

**Comment by libpitt** [comment]
https://github.com/hubmapconsortium/ingest-validation-tools/tree/phillips/cedar_tests/examples/dataset-examples

**Comment by libpitt** [comment]
Was able to run the CEDAR test using `./tests-manual/test-dataset-examples-cedar.sh <airflow_token> <cedar_api_key>` and saw some output. 
Findings:
- Couldn't install all packages listed requirements-dev.txt using python 3.10.9. Was able to install by manually running `pip install typed-ast ` Maybe need to indicate the exact version of python to use, understand it to be 3.10.12.
- Possible need to indicate introduction of CEDAR and how this differs from what was there before ... one or two lines
- Add in README.md how to run CEDAR
   - What is airflow token and how to obtain it
   - How to obtain CEDAR api token
